version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: investimentos
      POSTGRES_USER: development
      POSTGRES_PASSWORD: development
    ports:
      - 5432:5432
    volumes:
      - "./postgres/data:/var/etc/postgres/data"
